import os
import numpy as np
import scipy.linalg as sp_al


from compflowlab.utils import init_func
from compflowlab.utils import reshape_func
from compflowlab.boundary_condition import bc_func

def enKFcorrection(Q_en,Q_obs,H,R):
    
    """This function essentially performs a correction of each ensemble member at a 
    given time instance where data is available. It does this by adding a weighted multiple of the
    discrepancy or difference between the ensemble member and the observations at the given time
    instance. The weight factor is the Kalman gain, defined as:
    K = P*H^T(H*P*H^T+R)^-1 
    The definitions of the matrices P,H and R are provided above under 'inputs' """
    
    Ncells, N_e = Q_en.shape
    
    # compute ensemble mean
    Q_mean = np.mean(Q_en,0)
    
    # ensemble deviations
    Q_dev = Q_en - Q_mean
    
    # compute Covariance matrix
    P_en = np.dot(Q_dev,Q_dev.T)/(N_e-1)
    
    # Compute Kalman gain
    A = np.dot(P_en,H.T)
    B = np.dot(H,A)
    C = np.linalg.inv(B+R)
    
    K = np.dot(A,C)
    Q_a = np.zeros((Ncells,N_e))
    
    # Compute enKF corrections for each ensemble member
    for i in range(N_e):
        Q_num = Q_en[:,i] 
        Q_diff = np.dot(H,Q_obs) - np.dot(H,Q_num)
        
        Q_a[:,i] = Q_en[:,i] + np.dot(K,Q_diff)


def advance_one_time_step(solver_param,state,physics,time_integration,rom_param=None):

    ##############################################  
    # This function is taking one time step      #   
    # with data assimilated corrected adaptive   #
    # ROM framework. Where a normal adaptive ROM #
    # will be used but at specific freq. Solution#
    # generated by Static ROM will be used       # 
    # ensembles for data assimilation to correct #
    # the trajectory of AROM. Therefore it uses  #
    # the both adaptive ROM and static ROM       #
    # frameworks.                                #    
    ##############################################


    iter = solver_param['iter'] 
       

    # Initial Training of Adaptive ROM (FOM)

    if iter <= int(solver_param['FOM2ROM_trans_iter']):

        solver_param, state, rom_param = solver_param['AROM_solver'].advance_one_time_step(solver_param,state,physics,time_integration,rom_param)

    # Running Normal Adaptive ROM
    else:

        # data assimilation will be applied
        if iter % solver_param['unsampled_update_freq'] == 0:

            solver_param, state, rom_param   = solver_param['AROM_solver'].advance_one_time_step(solver_param,state,physics,time_integration,rom_param)

            Q_pre_da = state['Q_cons']

            # initialize a static ROM framework

            solver_param['training_start_iter'] = iter - solver_param['unsampled_update_freq']
            solver_param['training_step_iter' ] = 1
            solver_param['training_end_iter'  ] = iter

            rom_param   = solver_param['ROM_solver'].precomputer(solver_param)
            state['qr'] = rom_param['qr0']

            if solver_param['hyper']:

                from compflowlab.rom.sampling_func import hyper_precompute

                rom_param = hyper_precompute(solver_param,rom_param)

            # number of trial trajectories
            num_ensembles = 10

            # create an array to hold solutions of static ROM
            Q_rom  = np.zeros((solver_param['num_state_var']*solver_param['cell_number'],num_ensembles))

            # Run static ROM
            for e in range(num_ensembles):
                
                # create different initial conditions -- need to create a function to generate those
                Q0 = np.load(r'C:\GIT_Fork\ROMify\examples\sod_shock_tube\DACAROM_results\cons_prim\10iteration_cons.npy')

                state['Q_cons'] = reshape_func.solver_add_ghost(solver_param['cell_number'],
                                                                solver_param['num_state_var'],
                                                                Q0)

                for sub_iter in range(solver_param['unsampled_update_freq']):

                    solver_param, state, rom_param          = solver_param['ROM_solver'].advance_one_time_step(solver_param,state,physics,time_integration,rom_param)

                    print('Generating Ensemble: ' + str(e)+ ' - Iteration: ' + str(sub_iter) )    


                Q_rom[:,e] = reshape_func.solver_eliminate_ghost(solver_param['cell_number'],
                                                                 solver_param['num_state_var'],
                                                                 state['Q_cons'])

            # correct solution with data assimilation
            

        # only adaptive ROM with no extra treatment
        else:

            solver_param, state, rom_param   = solver_param['AROM_solver'].advance_one_time_step(solver_param,state,physics,time_integration,rom_param)


    return solver_param, state, rom_param